name:                game-of-life
version:             0.1.0.0
github:              "githubuser/game-of-life"
license:             BSD3
author:              "CozyDoomer"
maintainer:          "example@example.com"
copyright:           "2020 CozyDoomer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/game-of-life#readme>

dependencies:
- base >= 4.7 && < 5
- array
- unix

library:
  source-dirs: src

executables:
  game-of-life:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life

tests:
  game-of-life-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life
